### PR TITLE
Fix issue #6 Added Gravatar avatar

### PR DESCRIPTION
**Pull request by jonatanrdsantos**
# Added support for Gravatar.

Gravatar use email, not username.

### CODE REVIEW

**Comment by leggetter** [comment]
Attribute should doesn't really work in that case IMO. `email=` would be
clearer.

Might also be nice to offer a `email-hash=` or something to hide actual
email.

**Comment by jonatanrdsantos** [comment]
:+1:

**Comment by zenorocha** [comment]
Closing this one in favor of #20. Thanks for contributing @joridos ;)

**Comment by jonatanrdsantos** [comment]
Oks :smile:

**Pull request closed without merging**
